services:
  server:
    image: courtesi/hardcore_mc
    build:
      context: .
    environment:
      - VERSION=latest
      - RCON_PASSWORD=minecraft
      - RCON_PORT=25575
      - EXTRA_COMMANDS_FILE=extra_commands.txt
    volumes:
      - ./data:/app
    ports:
      - "25565:25565"
      - "25575:25575"
    tty: true
    stdin_open: true
